version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "3002:3000"
    networks:
      - software
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017/test"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - software
    volumes:
      - $PWD/mongo-data:/data/db'

networks:
  software:
    driver: bridge
